"""
API Application Entry Point

Assembles the FastAPI application:
  - Mounts Phase 5.2 Session Router  (/sessions CRUD)
  - Mounts Phase 5.3 Chat Router     (/sessions/{id}/messages)
  - Registers Phase 5.4 Error Handlers (KeyError → 404, etc.)
  - Adds CORS middleware (allow all origins for local dev)
  - Exposes GET /health for uptime checks

How to run locally:
  uvicorn api.app:app --reload --port 8000

Interactive docs (auto-generated by FastAPI):
  http://localhost:8000/docs   — Swagger UI
  http://localhost:8000/redoc  — ReDoc
"""

from __future__ import annotations
import os
import logging

from dotenv import load_dotenv
load_dotenv()   # load GROQ_API_KEY, CHROMA_* from .env for local dev

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from .phase_5_2_session_router import router as session_router
from .phase_5_3_chat_router     import router as chat_router
from .phase_5_4_error_handler   import register_handlers
from .phase_5_1_schemas         import HealthResponse

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# App
# ---------------------------------------------------------------------------

app = FastAPI(
    title="Mutual Fund FAQ Assistant",
    description=(
        "Factual Q&A for 5 HDFC mutual fund schemes (Direct Growth plans). "
        "No investment advice. Sources: Groww fund detail pages, refreshed daily at 9:15 AM IST."
    ),
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
)

# ---------------------------------------------------------------------------
# CORS — allow all origins for local dev; restrict in production
# ---------------------------------------------------------------------------

_ALLOWED_ORIGINS = os.getenv("ALLOWED_ORIGINS", "*").split(",")

app.add_middleware(
    CORSMiddleware,
    allow_origins=_ALLOWED_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ---------------------------------------------------------------------------
# Routers
# ---------------------------------------------------------------------------

app.include_router(session_router)
app.include_router(chat_router)

# ---------------------------------------------------------------------------
# Error handlers (Phase 5.4)
# ---------------------------------------------------------------------------

register_handlers(app)

# ---------------------------------------------------------------------------
# Health check
# ---------------------------------------------------------------------------

@app.get(
    "/health",
    response_model=HealthResponse,
    tags=["System"],
    summary="Health check",
    description="Returns `{status: ok}` when the server is running.",
)
def health() -> HealthResponse:
    return HealthResponse(status="ok", version="1.0.0")
